
//
//  AppDelegate+ETPushConstants.h
//  Generated by the Salesforce Marketing Cloud App Accelerator.
//

#import "AppDelegate.h"

@interface AppDelegate (ETPushConstants)


// application debug id
FOUNDATION_EXPORT NSString *const kETAppID_Debug;
// access token debug
FOUNDATION_EXPORT NSString *const kETAccessToken_Debug;
// application prod Id
FOUNDATION_EXPORT NSString *const kETAppID_Prod;
// access token prod
FOUNDATION_EXPORT NSString *const kETAccessToken_Prod;

FOUNDATION_EXPORT NSString *const kMessageTypeLocation;
FOUNDATION_EXPORT NSString *const kUserDefaultsLastPushReceivedDate;
FOUNDATION_EXPORT NSString *const kUserDefaultsPushUserInfo;
FOUNDATION_EXPORT NSString *const kUserDefaultsMessageType;
FOUNDATION_EXPORT NSString *const kUserDefaultsAlertText;
FOUNDATION_EXPORT NSString *const kMessageDetailCustomKeyDiscountCode;
FOUNDATION_EXPORT NSString *const kPushDefineOpenDirectPayloadKey;
FOUNDATION_EXPORT NSString *const kPushDefineCloudPagePayloadKey;
FOUNDATION_EXPORT NSString *const kPushDefinePersistentNotificationKey;

@end
