//
//  AppDelegate+ETPushConstants.m
//  Generated by the Salesforce Marketing Cloud App Accelerator.
//

#import "AppDelegate+ETPushConstants.h"

@implementation AppDelegate (ETPushConstants)

// Code@ AppIDs and Access Tokens for the debug and production versions of your app
// These values should be stored securely by your application or retrieved from a remote server
NSString *const kETAppID_Debug                       = @"39e5b390-27ae-4844-be24-cbe858d7fdc9";
NSString *const kETAccessToken_Debug                 = @"udsrye8sszckfa9dgkdh5jxn";
NSString *const kETAppID_Prod                        = @"cc868934-afe4-4b27-901c-c1a53d5d9fcb";
NSString *const kETAccessToken_Prod                  = @"z9jr695rxjtznzr9sx8yu25c";

// Constants used for Strings
NSString *const kMessageTypeLocation                 = @"Location";
NSString *const kUserDefaultsLastPushReceivedDate    = @"ud_lastPushReceivedDate";
NSString *const kUserDefaultsPushUserInfo            = @"ud_pushUserInfo";
NSString *const kUserDefaultsMessageType             = @"ud_messageType";
NSString *const kUserDefaultsAlertText               = @"ud_alertText";
NSString *const kMessageDetailCustomKeyDiscountCode  = @"discount_code";
NSString *const kPushDefineOpenDirectPayloadKey      = @"_od";
NSString *const kPushDefineCloudPagePayloadKey       = @"_x";
NSString *const kPushDefinePersistentNotificationKey = @"_p";

@end
