//
//  AppDelegate+ETPush.h
//  Generated by the Salesforce Marketing Cloud App Accelerator.
//

#import "AppDelegate.h"

@interface AppDelegate (ETPush)

- (BOOL)application : (UIApplication *)application shouldInitETSDKWithOptions : (NSDictionary *)launchOptions;

@end
