
//
//  AppDelegate+ETPushConstants.h
//  Generated by the Salesforce Marketing Cloud App Accelerator.
//

#import "AppDelegate.h"

@interface AppDelegate (ETPushConstants)

FOUNDATION_EXPORT NSString *const kETAppID_Debug;
FOUNDATION_EXPORT NSString *const kETAccessToken_Debug;
FOUNDATION_EXPORT NSString *const kETAppID_Prod;
FOUNDATION_EXPORT NSString *const kETAccessToken_Prod;
FOUNDATION_EXPORT NSString *const kMessageTypeLocation;
FOUNDATION_EXPORT NSString *const kUserDefaultsLastPushReceivedDate;
FOUNDATION_EXPORT NSString *const kUserDefaultsPushUserInfo;
FOUNDATION_EXPORT NSString *const kUserDefaultsMessageType;
FOUNDATION_EXPORT NSString *const kUserDefaultsAlertText;
FOUNDATION_EXPORT NSString *const kMessageDetailCustomKeyDiscountCode;
FOUNDATION_EXPORT NSString *const kPushDefineOpenDirectPayloadKey;
FOUNDATION_EXPORT NSString *const kPushDefineCloudPagePayloadKey;
FOUNDATION_EXPORT NSString *const kPushDefinePersistentNotificationKey;

@end
